# PostgreSQL Database (Render)
spring.datasource.url=jdbc:postgresql://dpg-d3gjnsfdiees73d75vd0-a.singapore-postgres.render.com/moneymanager_a8qx

spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
