# PostgreSQL Database (Render)
spring.datasource.url=jdbc:postgresql://dpg-d4fjov49c44c73br8p20-a.singapore-postgres.render.com/moneymanager_insha
spring.datasource.username=moneymanager_insha_user
spring.datasource.password=4JyiXhQsQHii5qUloFgEpjqTaPQXzICi

spring.datasource.driver-class-name=org.postgresql.Driver